name: Deploy Next.js application
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Create .env file
        run: echo "SITE_URL=${{ secrets.SITE_URL }}" >> .env
      - name: Build docker image
        run: docker build -t jenkinsguru/nextjs-app .
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Publish image to dockerhub
        run: docker push jenkinsguru/nextjs-app:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull jenkinsguru/nextjs-app:latest
      - name: Delete old container if exists
        run: docker rm -f nextjs-app-container
      - name: Run docker container
        run: docker run -d -p 3000:3000 --name nextjs-app-container jenkinsguru/nextjs-app
